using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace OMS.DrugService.Migrations
{
    /// <inheritdoc />
    public partial class Mag01 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Drugs",
                columns: table => new
                {
                    Drug_Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    Drug_Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Manufacturer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Side_Effects = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Disclaimer = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Category = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Consume_Type = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Image = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Price = table.Column<decimal>(type: "decimal(18,2)", nullable: false),
                    Count_In_Stock = table.Column<int>(type: "int", nullable: false),
                    Expiry_Date = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Created_By = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Upadted_By = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Created_At = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Upadated_By = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Drugs", x => x.Drug_Id);
                });

            migrationBuilder.CreateTable(
                name: "Logs",
                columns: table => new
                {
                    Log_Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    User = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Logs", x => x.Log_Id);
                });

            migrationBuilder.InsertData(
                table: "Drugs",
                columns: new[] { "Drug_Id", "Category", "Consume_Type", "Count_In_Stock", "Created_At", "Created_By", "Description", "Disclaimer", "Drug_Name", "Expiry_Date", "Image", "Manufacturer", "Price", "Side_Effects", "Upadated_By", "Upadted_By" },
                values: new object[,]
                {
                    { new Guid("01dbd3dd-35c2-48e5-a611-bd7d5fe3cc18"), "HMG-CoA reductase inhibitors, or statins.", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to lower cholesterol and triglyceride levels.", "Consult your doctor before use.", "Atorvastatin", "2025-1-15", "https =//cdn01.pharmeasy.in/dam/products/J21424/atorvastatin-10-mg-tablet-10-medlife-pure-generics-combo-3-1626532296.jpg", "Pfizer Inc.", 60m, "Muscle pain, nausea, headache", null, null },
                    { new Guid("0454ee7a-cd98-40bf-aaf0-c35ae7de7abb"), "antibiotics", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Antibiotic used to treat bacterial infections.", "Complete the full course as prescribed.", "Amoxicillin", "2024-12-01", "https =//5.imimg.com/data5/SELLER/Default/2023/8/332350358/SI/JT/VF/98283251/amoxicillin-drugs3.jpg", "GlaxoSmithKline plc", 62m, "Diarrhea, rash, nausea.", null, null },
                    { new Guid("048e2deb-2827-4515-b1ad-27443f1cace0"), "blood pressure ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Treats high blood pressure and heart failure.", "Monitor blood pressure regularly.", "Lisinopril", "2025-06-30", "https =//encrypted-tbn0.gstatic.com/images?q=tbn =ANd9GcRquzMUwap3aIcmZQhZ4FOztWQorUZSonP4wg&s", "AstraZeneca plc", 40m, "Dizziness, headache, fatigue.", null, null },
                    { new Guid("0e18b850-5379-4d79-bb78-65401701d8e2"), " Diabetes", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to control blood sugar levels in type 2 diabetes.", "Follow your diet and exercise program.", "Metformin", "2025-04-10", "https =//5.imimg.com/data5/SELLER/Default/2023/8/332774949/NY/WA/ZJ/6299000/metformin-hydrochloride-tablets.jpeg", " Merck & Co., Inc.", 31m, "Stomach upset, diarrhea, nausea.", null, null },
                    { new Guid("136c0bc5-5303-46fb-aed4-c1deebd3f78b"), "gastroesophageal ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Treats gastroesophageal reflux disease (GERD).", "Do not exceed the recommended dose.", "Omeprazole", "2024-09-20", "https =//5.imimg.com/data5/JD/FH/VU/SELLER-5478572/omeprazole-capsules-20mg.jpeg", "Novartis AG", 75m, "Headache, stomach pain, nausea.", null, null },
                    { new Guid("1b3fc741-74d0-41e7-933b-cc623768d863"), " blood pressure", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat high blood pressure and angina.", "Avoid sudden discontinuation.", "Amlodipine", "2025-08-15", "https =//5.imimg.com/data5/SELLER/Default/2023/1/CP/LY/QV/88793954/amlodipine-tablets-ip.jpeg", "Pfizer Inc.", 20m, "Swelling, dizziness, fatigue.", null, null },
                    { new Guid("1bfe06a0-4b21-486d-8d07-ca72ba9278fb"), "Insomnia ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Treats insomnia.", "Use only when you can get a full night's sleep.", "Zolpidem", "2024-11-30", "https =//5.imimg.com/data5/SELLER/Default/2023/9/342848763/LR/GK/WN/197293575/zolpidem-10-mg-tablet.jpg", "Sanofi S.A.", 70m, "Drowsiness, dizziness, diarrhea.", null, null },
                    { new Guid("1c893513-0956-4cb4-8eae-3fbe42a82943"), "depression ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat seizure and panic disorders.", "May be habit-forming, use as prescribed.", "Clonazepam", "2025-05-10", "https =//5.imimg.com/data5/SELLER/Default/2021/5/CR/QB/QR/3184985/clonvul0-5.jpg", "F. Hoffmann-La Roche AG", 350m, "Drowsiness, dizziness, fatigue.", null, null },
                    { new Guid("1d2012b0-b8d0-4640-b2df-31459cef3ba2"), "allergy ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat allergies and prevent asthma attacks.", "Not for use in an acute asthma attack", "Montelukast", "2024-12-05", "https =//www.glamrisdermacare.com/wp-content/uploads/2021/08/0000s_0006_BILAZIL-M-min.jpg", "Merck & Co., Inc.", 150m, "Headache, stomach pain, cough.", null, null },
                    { new Guid("1fa3d194-9491-40bf-9e24-84472516c14f"), "anticonvulsants", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", " Used to treat nerve pain and seizures.", "Avoid alcohol while taking this medication.", "Gabapentin", "2025-07-25", "https =//5.imimg.com/data5/SELLER/Default/2023/5/311267943/ZR/MT/QJ/69086821/gabapentin-100mg-tablet-500x500.jpg", "Pfizer Inc.", 131m, "Dizziness, drowsiness, coordination problems.", null, null },
                    { new Guid("227cdab3-1c65-416d-8603-cb399c750a31"), "Inhaler", "Inhalation", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat bronchospasm.", " Use only as prescribed by your doctor.", "Albuterol", "2024-10-10", "https =//5.imimg.com/data5/SELLER/Default/2023/8/337313153/HK/FV/II/57623134/buy-albuterol-hfa-90-mcg-inhaler-online.jpg", "Teva Pharmaceutical Industries Ltd.", 34m, "Nervousness, shaking, headache.", null, null },
                    { new Guid("22d24e79-9dba-4805-b7da-73aac3f8e552"), " Antihistamine", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Antihistamine used to relieve allergy symptoms.", " Do not exceed the recommended dose.", "Loratadine", "2025-03-01", "https =//5.imimg.com/data5/SELLER/Default/2023/8/332709645/ER/VU/LD/6299000/loratadine-10-mg-tablets.jpeg", "Bayer AG", 62m, " Dry mouth, headache, drowsiness.", null, null },
                    { new Guid("23822b9e-8dfe-4065-80d4-ecf68015a579"), " inflammatory", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to reduce fever and treat pain or inflammation.", "Do not exceed the recommended dose.", "Ibuprofen", "2025-09-15", "https =//5.imimg.com/data5/SELLER/Default/2023/6/319597573/MH/NE/SR/135658020/ibuprofen-400-mg-bp-tablets.jpg", " Johnson & Johnson", 70m, "Stomach pain, heartburn, nausea.", null, null },
                    { new Guid("2456fc1e-37c8-46db-87f6-e15089dd8dda"), "blood pressure", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to prevent blood clots.", "Regular blood tests are required.", "Warfarin", "2025-02-28", "https =//www.careformulationlabs.com/uploaded_files/warfarin-5.png", "Bristol-Myers Squibb Company", 71m, "Bleeding, bruising, nausea.", null, null },
                    { new Guid("26507701-358c-4466-85c3-5906a6ccb15b"), "Antihistamine", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Antihistamine used to treat allergy symptoms.", "Do not use machinery if drowsy.", "Cetirizine", " 2025-05-15", "https =//5.imimg.com/data5/SELLER/Default/2023/5/311971664/FU/KT/PV/11858298/cetirizine-tablet.webp", "UCB S.A.", 26m, "Drowsiness, dry mouth, fatigue.", null, null },
                    { new Guid("29ed605c-76c1-4c10-a2d7-962227a5e035"), "depression", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Antidepressant used to treat depression and anxiety.", "May take several weeks to feel the full benefit.", "Sertraline", "2025-06-10", "https =//5.imimg.com/data5/SELLER/Default/2023/8/337366367/KI/RJ/BA/7034457/sertraline-100-mg-tablets.jpg", " Pfizer Inc.", 260m, "Nausea, insomnia, dry mouth.", null, null },
                    { new Guid("2a244008-1dfe-4817-bf98-7060e69332ab"), "Pain Killer ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", " Used to treat moderate to severe pain.", "Can be habit-forming, use only as prescribed.", "Tramadol", "2025-08-20", "https =//5.imimg.com/data5/SELLER/Default/2023/8/331683629/YW/EW/FV/1359917/tramadol-hydrochloride-paracetamol-tablets.jpg", " Janssen Pharmaceuticals", 17m, "Dizziness, nausea, constipation.", null, null },
                    { new Guid("2fced847-3d4b-4cad-99da-8a0a08660b80"), " Gynaecology", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat symptoms of an enlarged prostate.", " Take 30 minutes after the same meal each day.", "Tamsulosin", "2025-04-05", "https =//5.imimg.com/data5/GLADMIN/Default/2024/1/382027832/MW/YF/DV/37869803/tamsulosin-hydrochloride-tablet.png", " Boehringer Ingelheim GmbH", 85m, "Dizziness, headache, runny nose.", null, null },
                    { new Guid("30a99895-c7f9-4f97-8cb7-03c03a891411"), "Pain Killer", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat moderate to severe pain.", "High potential for abuse, use as prescribed.", "Oxycodone", "2025-07-30", "https =//tajgenerics.com/wp-content/uploads/cache/images/Oxycodone_7_5mg__Acetaminophen_375mg_Tablet_Exporters-scaled/Oxycodone_7_5mg__Acetaminophen_375mg_Tablet_Exporters-scaled-3481289551.jpg", " Purdue Pharma L.P.", 230m, "Nausea, drowsiness, constipation.", null, null },
                    { new Guid("31470cfa-e8c5-41ba-ac1d-8ad4a50928d3"), "corticosteroid", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Corticosteroid used to treat inflammation.", " Do not stop taking abruptly.", "Prednisone", "2025-09-01", "https =//5.imimg.com/data5/SELLER/Default/2022/12/CE/BE/CW/23808697/prednisone-500x500.JPG", " Mylan N.V.", 12m, "Insomnia, mood changes, weight gain.", null, null },
                    { new Guid("345fb265-fc39-491a-9521-9cce3aabbe8d"), " depression", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", " Antidepressant used to treat depression and OCD.", "May take several weeks to feel the full effect.", "Fluoxetine", "2025-10-10", "https =//5.imimg.com/data5/SELLER/Default/2022/9/GN/LY/IE/154048565/fluoxetine-10mg-tablet.png", "Eli Lilly and Company", 442m, "Nausea, drowsiness, insomnia.", null, null },
                    { new Guid("35b2570a-f47e-4eaa-85c5-55362fb4fb15"), " blood pressure", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", " Used to treat high blood pressure and angina.", " Do not stop taking abruptly", "Metoprolol", "2025-02-15", "https =//5.imimg.com/data5/SELLER/Default/2022/11/UO/RS/FG/161638739/metoprolol-tartrate-50-mg.jpg", " AstraZeneca plc", 48m, "Dizziness, tiredness, depression.", null, null },
                    { new Guid("3622ff82-b5bf-41e2-b3c8-bbe9afb633fb"), "depression ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat depression and anxiety.", "May take several weeks to feel the full effect.", "Duloxetine", "2025-11-05", "https =//5.imimg.com/data5/AL/LG/MY-6299000/duloxetine-30-mg-capsules.jpg", "Eli Lilly and Company", 100m, "Nausea, dry mouth, drowsiness.", null, null },
                    { new Guid("3b958543-2a83-4bfc-b97b-2fa114e0e00e"), " oop diuretics", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Diuretic used to treat fluid retention and swelling.", "Monitor electrolyte levels regularly.", "Furosemide", "2025-05-25", "https =//5.imimg.com/data5/SELLER/Default/2023/8/333795220/XM/UX/IJ/6299000/furosemide-tablet.jpeg", " Sanofi S.A.", 14m, "Dehydration, electrolyte imbalance, dizziness.", null, null },
                    { new Guid("3c838a0b-e152-4a19-bc53-5e6d157ea749"), "cholesterol ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to lower cholesterol and triglycerides.", "Follow a cholesterol-lowering diet plan.", "Simvastatin", "2025-08-10", "https =//5.imimg.com/data5/SELLER/Default/2023/10/357085613/HL/RR/GE/50963842/simvastatin-tablet-ups-20-mg.jpg", " Merck & Co., Inc.", 100m, "Muscle pain, headache, nausea.", null, null },
                    { new Guid("3d2b42fc-6443-4aa6-bc8f-aced3566930a"), "blood pressure ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat high blood pressure.", "Monitor blood pressure regularly.", "Losartan", "2025-01-25", "https =//5.imimg.com/data5/SELLER/Default/2023/12/373066330/IL/GL/IT/180648134/losartan-potassium-tablets-ip-500x500.jpg", " Bayer AG", 38m, "Dizziness, back pain, nasal congestion.", null, null },
                    { new Guid("4105d68b-74e4-458c-94ec-25bc5ce07cf7"), "antiplatelet", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to prevent blood clots.", "Regular blood tests are required.", "Clopidogrel", "2025-03-20", "https =//5.imimg.com/data5/SELLER/Default/2023/3/293106006/NJ/NS/EB/29765627/clopidogrel-75mg-aspirin-75mg-tab-500x500.jpg", " Sanofi S.A", 54m, "Bleeding, bruising, headache.", null, null },
                    { new Guid("41b7caed-1d30-4559-99fe-6c860be5e699"), "Pain killer ", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to treat severe pain.", "High potential for abuse, use as prescribed.", "Hydrocodone", "2025-07-05", "https =//t4.ftcdn.net/jpg/02/93/25/13/360_F_293251390_jBCMpaDN1V1ipxcqpthTt3yikZPAZMr8.jpg", " AbbVie Inc.", 259m, " Nausea, drowsiness, constipation.", null, null },
                    { new Guid("44338b3b-fdb6-4358-9f76-b86527ba8125"), " Depression", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", " Antidepressant used to treat depression and insomnia.", "May take several weeks to feel the full effect.", "Trazodone", "2025-06-15", "https =//c8.alamy.com/comp/GJ7J4D/molipaxin-100mg-capsules-antidepresant-trazodone-hydrochloride-GJ7J4D.jpg", " Teva Pharmaceutical Industries Ltd.", 185m, " Drowsiness, dry mouth, dizziness.", null, null },
                    { new Guid("4902693b-9a64-4164-84ef-6ee83f2834d9"), " H2 blockers", "Oral", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Used to reduce stomach acid and treat ulcers.", "Use as directed by your doctor.", "Ranitidine", "2024-12-20", "https =//wellonapharma.com/admincms/product_img/product_actual_img/Ranitidine%20Tablets_27-01-2017-08 =47 =41.jpg", "GlaxoSmithKline plc", 30m, " Headache, constipation, nausea.", null, null },
                    { new Guid("4a8125db-978f-4e06-8a8e-e9baabe70240"), "Dermatology", "Adult = Topical- As 0.05 or 0.1% cream/gel = Apply once in the evening.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a retinoid, prescribed for psoriasis and acne. It may decrease skin inflammation and skin changes associated with psoriasis.", "Use as directed by your doctor.", "Tazarotene", "2025-02-02", "https =//tiimg.tistatic.com/fp/1/006/419/tazarotene-cream-0-1--641.jpg", null, 420m, "Ski_D = Itching, burning/stinging, redness, skin peeling, irritation, worsening of psoriasis, rash, dry skin, bleeding, localized swelling, high cholesterol levels, desquamation, contact dermatitis, discoloration of skin and photosensitivity.", null, null },
                    { new Guid("4b440830-4046-4aea-9383-cf2bfabd9180"), "Dermatology", "Adult- PO- The recommended dose range is 0.5 to 1.0 mg/kg/day given in two divided doses with food for 15 to 20 weeks.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a retinoid, prescribed for acne and other skin disorders. It reduces skin oil production, changing the characteristics of the skin oil, and preventing abnormal hardening of the skin.", "Use as directed by your doctor.", "Isotretinoin ", "2025-12-23", "https =//i.postimg.cc/D0VJ7Lr1/iso.jpg", null, 299m, "Allergic reactions, fast heart rate and stroke.", null, null },
                    { new Guid("4bf2e9d6-cdac-4941-85c2-2721f21273fb"), "Dermatology", "Children over 12 years = 50mg every 12 hours, Adults The usual  dosage is 100 mg every 12 hours. The  dosage and duration varies according to the type of infection.For local use in the gums, the dose is 1mg given beneath the gums.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Minocycline is a broad spectrum tetracycline antibiotic. It acts by inhibiting the growth of bacteria in the body, It may be effective in other infections as well, however several bacteria have developed resistance to the drug, It may be used in patients who are allergic to the penicillin group of drugs as an alternative.", "Use as directed by your doctor.", "Minocycline", "2025-02-02", "https =//i.postimg.cc/JhvtQZdS/mino.png", null, 300m, "Los_D of appetite, nausea, vomiting, diarrhea, indigestion, mouth ulcer, discoloration of the tongue and difficulty in swallowing.", null, null },
                    { new Guid("4bffbb3b-f70b-4013-90dd-6c2b34c7d0eb"), "Dermatology", "Adult = Topical- Apply 1-4 times/day.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is an anti-itch medication that contains mixture of zinc oxide (ZnO) with about 0.5% iron (III) oxide, prescribed for itching skin conditions. This medication in some cases is used as a mild antiseptic to arrest infections caused by scratching the affected area. Calamine is proved to be an effective medication in acne treatment.", "Use as directed by your doctor.", "Calamine Lotion", "2025-12-23", "https =//i.postimg.cc/L6x9TjJv/calamine.jpg", null, 240m, "Rash or irritation.", null, null },
                    { new Guid("4d39a332-77fa-4572-aa34-d8e80eae2254"), "Dermatology", "Apply as directed by Physician", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is an emollient, prescribed for pediculosis, and other skin conditions.", "Use as directed by your doctor.", "Dimethicone", "2024-12-20", "https =//i.postimg.cc/K8K2DwSv/dim.jpg", null, 220m, "Rare_ly, redness, pain and irritation at the site of application.", null, null },
                    { new Guid("4d53b46d-c39a-4616-8e88-6f3f81b93315"), "Dermatology", "Adult- PO- The recommended  dosage for duodenal ulcer is 1 g four times per day on an empty stomach.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a gastric protective agent, prescribed for intestinal ulcers.", "Use as directed by your doctor.", "Sucralfate", "2025-02-02", "https =//i.postimg.cc/90x6GtL7/ss.jpg", null, 190m, "Dia_Drhea, nausea, vomiting, gastric discomfort, indigestion, flatulence and dry mouth, Itching and rash, Dizziness, sleeplessness, sleepiness and unsteadiness,Back pain and headache.", null, null },
                    { new Guid("4dcc4249-46c1-49e6-8d19-89a7d3147069"), "Dermatology", "Topical- A thin film of gel should be applied once a day to affected areas after washing the skin.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Adapalene is a topical retinoid-like compound used to treat mild to moderate acne by preventing the formation of pimples acting deeply in the source.It also prevents the formation of new() acne by restoring skin texture and tone.", "Use as directed by your doctor.", "Adapalene", "2025-12-23", "https =//i.postimg.cc/WbgzwdMH/adap.jpg", null, 320m, "A b_Dief sensation of warmth or stinging may occur immediately after applying the medication, redness, dryness, itching of the skin and scaling, mild burning, or worsening of acne may occur during the first 2-4 weeks of using the medication.", null, null },
                    { new Guid("52f52831-43f2-48e9-909a-2545ad662891"), "Dermatology", "Topical- Apply a thin layer to the affected area as directed by your physician.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a topical antibiotic, prescribed for acne vulgaris. It inhibits the enzyme DNA gyrase that is involved in bacterial replication.", "Use as directed by your doctor.", "Nadifloxacin", "2025-02-02", "https =//i.postimg.cc/NjNxBC5T/nad.png", null, 285m, "Itc_Ding, irritation, redness, flushes, papules, feeling of warmth, increased sweating, contact dermatitis and dryness of the skin.", null, null },
                    { new Guid("537f4369-cb6f-4668-82ba-eb1dc94443c5"), "Dermatology", "PO- The recommended dose range is 250 to 1.5gm in divided doses.Topical-Apply a thin layer over the affected skin 4 times per day.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is an antibiotic, prescribed for various infections such as acne, dermatitis, gonorrhea, etc.", "Use as directed by your doctor.", "Oxytetracycline", "2025-02-02", "https =//i.postimg.cc/nhMDYFhj/oxy.jpg", null, 225m, "Los_D of appetite, nausea, vomiting, diarrhea, tongue inflammation, difficulty in swallowing and inflammatory lesions.", null, null },
                    { new Guid("555863b7-49e4-4544-87af-a7783cdea340"), "Dermatology", "as directed by your physician.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a topical antibiotic, prescribed for acne vulgaris. It inhibits the enzyme DNA gyrase that is involved in bacterial replication.", "Use as directed by your doctor.", "Nadifloxacin", "2024-12-20", "https =//5.imimg.com/data5/FY/GY/MY-39084219/nadifloxacin-cream-500x500.jpg", null, 200m, "Itch_ing, irritation, redness, flushes, papules, feeling of warmth, increased sweating, contact dermatitis and dryness of the skin.", null, null },
                    { new Guid("555863b7-eb9d-4668-909a-11e5cbae5643"), "Diabetes", "PO - The initial dose is based on patient's condition. Maximum recommended dose is 25/2000mg.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Alogliptin is prescribed to reduce high blood sugar level in patients with type 2 diabetes along with diet control and exercise.It should not be used in treating diabetic ketoacidosis or type 1 diabetes.  ", "Use as directed by your doctor.", "Alogliptin", "2025-12-23", "https =//www.empr.com/wp-content/uploads/sites/7/2018/12/ac752944889a4c6494dae4f478ea8237-nesina_405478.jpg", null, 405m, "Upp_Dr respiratory tract infection, heart attack, throat inflammation, diarrhea, high blood pressure, headache, back pain and urinary tract infection.", null, null },
                    { new Guid("56c385a7-eb9d-49da-8d5e-be81ce4c141a"), "Diabetes", "(125mg/500mg)- Dose is based on patientâ€™s condition.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Alogliptin and Metformin combination is used along with diet and exercise to improve blood sugar control or to treat hyperglycemia in patients with type 2 diabetes.High blood sugar level can cause damage to the eyes, kidney, and nerves.This combination medication contains alogliptin, a dipeptidyl-peptidase-4 (DPP-4) inhibitor and metformin, a biguanide.", "Use as directed by your doctor.", "Alogliptin and Metformin", "2025-12-23", "https =//5.imimg.com/data5/ZJ/FV/VB/SELLER-104814248/alogliptin-500x500.jpg", null, 500m, "Lact_ic Acidosis and pancreatitis.Most Common = Upper respiratory tract infection, nasopharyngitis, diarrhea, hypertension, headache, back pain and urinary tract infection.", null, null },
                    { new Guid("588b3f8d-a353-479f-ad9a-d2006eb52a12"), "Diabetes", "Dose is based on patientâ€™s condition. Maximum recommended dose is 25/45mg.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Alogliptin and Pioglitazone combination is used to treat high blood sugar level in patients with type 2 diabetes along with diet control and exercise. This combination should not be used to treat type 1 diabetes.This combination medication contains pioglitazone, a thiazolidinedione agent and alogliptin, a DPP-4 inhibitor.", "Use as directed by your doctor.", "Alogliptin and Pioglitazone", "2025-12-23", "https =//www.empr.com/wp-content/uploads/sites/7/2018/12/5a26069609d944038725ae95e761a5f1-oseni_405485.jpg", null, 450m, "Inf_Dammation of throat and nasal passages, back pain and upper respiratory tract infection.", null, null },
                    { new Guid("5895021f-292a-4233-8b46-11e5cbae5643"), "Diabetes", "PO- The recommended initial dose is 100 mg once daily.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is an antidiabetic (sodium glucose co-transporter 2 (SGLT2) inhibitor), prescribed for type 2 diabetes mellitus along with diet and exercise. For patients with type 2 diabetes along with diabetic kidney disease, physicians should consider using an SGLT2 inhibitor when the eGFR is at or above 30, especially with albuminuria above 300 mg/g, to lower renal and CV risk as per A.D.A recommendations.", "Use as directed by your doctor.", "Canagliflozin", "2025-12-23", "https =//5.imimg.com/data5/MR/OX/MY-18174683/sulisent-28canagliflozin-100mg-29-tablet-500x500.jpg", null, 298m, "Fema_le genital mycotic infections, urinary tract infection and increased urination.", null, null },
                    { new Guid("5e0cfa38-c8a9-463c-830a-c516bcd39645"), "Diabetes", "PO- The recommended initial dose is 250mg/day. It may be adjusted based on patientâ€™s condition.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a sulfonylurea antidiabetic drug, prescribed for type 2 diabetes. This medication helps to keep blood sugar levels under control.", "Use as directed by your doctor.", "Diabinese", "2025-12-23", "https =//encrypted-tbn0.gstatic.com/images?q=tbn =ANd9GcSKl6UBEBhkp0cUc7ciO3VVRoBjtAf7cA-QPOTggzDmit4AYegpA3mcl9haEtf6nfB5diw&usqp=CAU", null, 345m, "Bod_D as a Whole  = Low blood sugar, Disulfiram-like,Central Nervous System  = Dizziness and headache, Gastrointestinal  = Diarrhea, nausea, vomiting, loss of appetite and hunger, Liver  = Jaundice, Skin  = Itching and hives, Blood  = Anemia and decrease in blood counts.", null, null },
                    { new Guid("607f81c3-6d7e-45ca-9a5d-2aca5ee75bb0"), "Diabetes", "For hypercholesterolesmia- The recommended dose is one 3.75-gram packet once daily or one 1.875-gram packet twice daily.For Type 2 Diabetes- The recommended dose is 6 tablets once daily or 3 tablets twice daily.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a bile acid sequestrant, prescribed for familial hypercholesterolesmia and type 2 diabetes with other medications.", "Use as directed by your doctor.", "Colesevelam HCL", "2025-12-23", "https =//www.prestoimages.net/store30/rd14324/14324_pd3794145_1_.jpg", null, 400m, "Hea_Dache, fatigue, increased level of liver enzyme, runny nose, vomiting, constipation, indigestion, difficulty in swallowinglow blood sugar, nausea and high blood pressure..", null, null },
                    { new Guid("625b58c4-6354-4302-9cce-e846deefd3b4"), "Diabetes", "The recommended initial dose of ertugliflozin tablets is 5 mg to be taken once a day.The dose of ertugliflozin can be increased to 15 mg once daily to achieve adequate glycemic control", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Ertugliflozin tablet is a sodium glucose co-transporter 2 (SGLT2) inhibitor which is prescribed for adult patients with type 2 diabetes as an adjunct therapy to diet control and exercise with a focus to improve glycemic control.It is prescribed either as a monotherapy or in combination with metformin or sitagliptin.  ", "Use as directed by your doctor.", "Steglatro", "2025-12-23", "https =//emedz.net/blog/wp-content/uploads/2020/01/Steglatro-ertugliflozin-696x484.jpg", null, 500m, "Com_Don = Frequent urination, low blood sugar level, genital fungal infections, Gastrointestinal = Nausea, pain in the stomach, vomiting, Cardiovascular = Low blood volume, low blood pressure, faster heartbeat, increased LDL-cholesterol level in blood, Nervous system = Confusion, dizziness, headache, irritability, weakness, Respiratory = Difficulty in breathing, nasopharyngitis, Kidney = Urinary tract infections (pyelonephritis, urosepsis or bladder infections), pain or burning sensation while passing urine, blood in urine, reduced kidney function, Others = Foot ulcers or sores, fever, pain or tenderness in the lower limbs, pain in the back, reduced weight, increased thirst", null, null },
                    { new Guid("634863c9-8731-432b-8993-389062c3a743"), "Diabetes", "Adult- The initial dose is 5 mcg injected under the skin (subcutaneously) twice daily, 60 minutes before breakfast or dinner.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a incretin mimetic, prescribed for type 2 diabetes with diet and exercise, either alone or with other medications. For patients with chronic kidney disease who are at elevated risk for CV events, a glucagon-like peptide 1 receptor agonist may lower risk for albuminuria progression and/or CV events, according to new() (2019)recommendations of The American Diabetes Association It works by stimulating the pancreas to secrete insulin in hyperglycemic condition.  ", "Use as directed by your doctor.", "Byetta", "2025-12-23", "https =//5.imimg.com/data5/SELLER/Default/2021/2/KR/IZ/EH/123113767/byetta-10mcg-500x500.jpg", null, 395m, "Mos_D Common = Nausea.Central Nervous System = Dizziness or lightheadedness, nervousness, mood changes, weakness, shakiness, confusion, epilepsy and loss of consciousness.Gastrointestinal = Extreme thirst, extreme hunger, stomach upset, vomiting, diarrhea and difficulty in swallowing. Skin = Rash, hives and itching. Allergic reactions = Swelling of the face, throat, tongue, lips, eyes, hands, feet, ankles, or lower legs and difficulty in breathing.", null, null },
                    { new Guid("6694147d-65c9-4db4-9896-8a02e8319177"), "Diabetes", "The treatment is started with a low dose of 2.5 mg per day, and increased up to a maximum of 20 mg per day according to the blood glucose levels.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "TGlibenclamide is an oral hypoglycemic (glucose lowering) drug used to control blood sugar levels in patients with type 2 diabetes in addition to diet and exercise.It belongs to the chemical group of sulfonylureas", "Use as directed by your doctor.", "Glibenclamide", "2025-12-23", "https =//5.imimg.com/data5/QY/WA/MY-29865653/glibenclamide-tablets-500x500.jpg", null, 456m, "Dig_Dstive tract = Nausea, vomiting, flatulence, abdominal fullness, diarrhea, constipation, heartburn, liver dysfunction, Skin = Rash, skin swelling, photosensitivity reactions (skin reactions following exposure to sunlight) including porphyria cutanea tarda (which is associated with an enzyme deficiency, Blood = Low blood counts, low blood glucose levels, low blood sodium levels, Others = Tiredness, weakness, fever, other allergic reactions, weight gain, joint or muscle pain.", null, null },
                    { new Guid("71d1df18-9c3e-4599-affe-c54a325a592e"), "Depression", " Oral = 400-1600 mg per day", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Ademetionine is used for treating chronic liver disease such as intrahepatic cholestasis.", "Use as directed by your doctor.", "Ademetionine", "2025-12-23", "https =//i.postimg.cc/Z5Y1wQGy/Ademetionine.jpg", null, 345m, "Nerv_ous system disorders = Headache, insomnia, dizziness, nervousness", null, null },
                    { new Guid("7205d1c2-3503-49f8-b4b4-07d47f98cb52"), "Depression", "The starting dose for treating anxiety is 0.25-0.5 mg, 3 times daily using immediate release tablets.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a benzodiazepine, prescribed for anxiety and panic disorders.", "Use as directed by your doctor.", "Alprazolam", "2025-12-23", "https =//i.postimg.cc/KYkpVhJ4/Alprazolam.jpg", null, 765m, "Gas_Drointestinal  = Dry mouth, constipation, diarrhea, nausea/vomiting and increased salivation.", null, null },
                    { new Guid("732a381c-b456-444b-aba7-628c90aa9264"), "Depression", "Adult = PO- Depression- Initial =50-75 mg/day; up to 150 mg/day if needed.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a tricyclic antidepressant, prescribed for depression.", "Use as directed by your doctor.", "Amitriptyline", "2025-12-23", "https =//i.postimg.cc/TYtk33sp/Amitriptyline.jpg", null, 987m, "All_Drgic  = Skin rash, hives, photosensitivity, swelling of the face and tongue.", null, null },
                    { new Guid("74aee27c-15af-480d-966b-a2377f2ce712"), "Dental", "As 0.2% solution = Rinse with 10 ml for 1 min 2-3 times/day.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a chemical antiseptic, prescribed for gingivitis, cleansing skin and wound areas.", "Use as directed by your doctor.", "Chlorhexidine", "2025-12-23", "https =//i.postimg.cc/nrDHcWFL/Chlorhexidine.jpg", null, 300m, "Skin_ sensitivity, irritation of eye, mucosal irritation and staining of the teeth and tongue.", null, null },
                    { new Guid("753752f9-ea3a-48fe-aaae-9c85c754131b"), "Dental", "Feracrylum is available as a 1% sterile solution (1% w/v feracrylum), as 50 and 15 gm gel tubes (1% w/w feracrylum) and tulle ( 3% w/v feracrylum).", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Feracrylum is used as a hemostatic (to stop bleeding) and an anti-septic for the management of post-operative wounds, cuts.", "Use as directed by your doctor.", "Feracrylum", "2025-12-23", "https =//i.postimg.cc/W4ztcXkd/Feracrylum.jpg", null, 620m, "Gastrointestinal = Nausea, stomach pain.", null, null },
                    { new Guid("7ad75bb3-b7e9-49f5-86da-a0866431991f"), "Dental", "The recommended dose of the drug is 20mg/0.2ml injection.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Gensparin prevents the formation of blood clots and is hence used for the treatment of thrombolytic disorders.", "Use as directed by your doctor.", "Gensparin", "2025-12-23", "https =//i.postimg.cc/FH7Q9qTX/Gensparin.jpg", null, 854m, " Skin = Rashes, pale skin, clots at the puncture site.", null, null },
                    { new Guid("7cdea7f7-aa7b-4671-82d4-cc34a49e7966"), "Dental", "Dose is based on patientâ€™s condition.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is an essential nutrient, prescribed for patients with vitamin deficiency.  Normally provided in combination with dietary minerals.", "Use as directed by your doctor.", "Multivitamin", "2025-12-23", "https =//i.postimg.cc/3r1M276H/Multivitamin.jpg", null, 790m, "Slight nausea and unpleasant taste.", null, null },
                    { new Guid("8941f8e0-e770-4ce9-97d1-3a709a296a33"), "Fracture", " The recommended adult dose is 80 mcg to be given subcutaneously (just under the skin) once a day", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Abaloparatide is prescribed to treat osteoporosis in postmenopausal women who are at a high risk for fracture.", "Use as directed by your doctor.", "Abaloparatide", "2025-12-23", "https =//i.postimg.cc/MGStsfM3/Abaloparatide.jpg", null, 350m, "â€¢_D Gastrointestinal = Nausea, pain in upper abdominal area, constipation, upset stomach.", null, null },
                    { new Guid("8b4f83cb-17a1-4075-858a-1471de2f4d30"), "Fracture", "The usual dosage is one tablet every 6 hours as needed for pain.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This combination medication is used to relieve moderate to severe pain.", "Use as directed by your doctor.", "Aspirin and Oxycodone ", "2025-12-23", "https =//i.postimg.cc/C5XsbRpN/Aspirin-and-Oxycodone.jpg", null, 705m, " Mo_Dt common  = Lightheadedness, dizziness, drowsiness or sedation, nausea and vomiting.", null, null },
                    { new Guid("90307545-dbae-41b1-ba24-1358c45565bb"), "Fracture", "The recommended oral adult dose for metamizole is 500 mg 3-4 times up to a maximum dose of 4000 mg/day.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Metamizole is a painkiller used for the treatment of fever, headache, toothache, postoperative pain and other painful conditions.", "Use as directed by your doctor.", "Metamizole", "2025-12-23", "https =//i.postimg.cc/g0syNSPr/Metamizole.jpg", null, 432m, "Skin = Severe skin reactions like toxic epidermal necrolysis", null, null },
                    { new Guid("95016060-381d-4eee-96ce-1f9717e8f89c"), "Women Care", "Adult- The recommended dose range is 25 to 400 mg/day.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is a hormone, prescribed for replacement therapy in women who have passed menopause. It is also used to prevent uterine cancer.", "Use as directed by your doctor.", "Progesterone", "2025-12-23", "https =//new()assets.apollo247.com/pub/media/catalog/product/s/u/sus0048.jpg", null, 285m, "Gast_rointestinal  = Abdominal pain, nausea, vomiting, abdominal distension and constipation. General  = Fatigue. Central Nervous System  = Headache.urinary tract infections.", null, null },
                    { new Guid("95987b69-82d8-4c1c-8847-6a7718536705"), "Women Care", "The dose varies according to the condition.The usual recommended oral dose for dehydroepiandrosterone is 50 to 75 mg/day. Higher doses of 50 mg three times a day have been used for adrenal insufficiency.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Adrenal insufficiency, where the adrenal gland does not produce enough hormones, To improve aging skin, Depression", "Use as directed by your doctor.", "Dehydroepiandrosterone", "2025-12-23", "https =//i.postimg.cc/rpZgNVWK/de.jpg", null, 420m, "Changes in blood pressure, reduced HDL cholesterol levels", null, null },
                    { new Guid("95ca7d10-8d4c-4abf-8fa8-e4f2675b6ed5"), "Women Care", "Adult- IV/IM/PO = The recommended dose range is 0.3 to 25mg.", 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "This medication is prescribed for severe vasomotor symptoms due to menopause, ovarian failure, osteoporosis, uterine bleeding, delayed puberty and prostate cancer.", "Use as directed by your doctor.", "Estrogen", "2025-12-23", "https =//i.postimg.cc/8zB0Mgt6/es.jpg", " Bayer AG", 320m, "Gas_Drointestinal  = Stomach upset, vomiting, heartburn, constipation, diarrhea and gas. Central Nervous System  = Nervousness, depression, dizziness, tight muscles, weakness, tingling and movement disorders. Metabolic  = Weight gain or loss and loss of appetite. Skin  = Hair loss, unwanted hair growth and darkening of the skin, Musculoskeletal  = Leg cramps and joint pain. Allergic Reactions  = Rash, blisters, hives, itching, swelling of the eyes, face, tongue, throat, hands, arms, feet, ankles or lower legs, hoarseness, difficulty in breathing or swallowing. Miscellaneous  = Sore throat, fever, chills, cough and other signs of infection.", null, null },
                    { new Guid("95cd4507-2ee5-45a8-8e2d-eeac6ba9559b"), "women care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "A lu_xurious cream that rejuvenates and hydrates your skin, giving it a youthful glow.", "Consult with a dermatologist before use if you have sensitive skin.", "Skin Rejuvenation Cream", "2025-05-20", "https =//rukminim2.flixcart.com/image/750/900/xif0q/fairness/i/1/y/50-skin-rejuvenation-night-cream-50g-1-staylesta-original-imagtd7z2z5fzhg9.jpeg?q=20&crop=false", "BeautyCo", 407m, "May cause mild irritation in sensitive skin.", null, null },
                    { new Guid("98257419-c322-4348-bad2-59fc2bc251f0"), "women care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Supe_r absorbent ultra-thin pads for all-day comfort and protection.", "Always read the label. Use only as directed.", "Whisper Choice Ultra-Thin Pads", "2025-06-30", "https =//www.quickpantry.in/cdn/shop/products/whisper-choice-ultra-sanitary-pads-extra-long-xl-6-pads-quick-pantry_512x520.jpg?v=1710538389", "Whisper", 49m, "None reported. If irritation occurs, discontinue use.", null, null },
                    { new Guid("99dd0620-250a-4cd2-9236-95c9bdb4d8a5"), "women care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Desi_gned for maximum absorbency and comfort during the night.", "Always read the label. Use only as directed.", "Sofy Bodyfit Overnight Pads", "2025-12-31", "https =//www.bigbasket.com/media/uploads/p/xl/40023141_3-sofy-bodyfit-overnight-pads-xxxl.jpg", "ComfortPlus", 78m, "None reported. If irritation occurs, discontinue use.", null, null },
                    { new Guid("9e89c5c1-db3a-42f0-b867-730b9ea5e2f1"), "women care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Preg_anew()s is a pregnancy test kit that provides accurate results in just 5 minutes.", "This product is not a substitute for professional medical advice. Consult a healthcare provider for any health-related questions.", "Preganew()s", "2025-12-31", "https =//www.netmeds.com/images/product-v1/600x600/108125/prega_new()s_card_device_1s_36927_0_2.jpg", "Mankind Pharma", 60m, "No known side effects when used as directed.", null, null },
                    { new Guid("9ea2bbf5-263b-4d5f-bea6-508a3295983c"), "women care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Gent_le feminine wash with natural ingredients for daily hygiene.", "For external use only. Discontinue use if irritation occurs.", "V Wash", "2024-11-15", "https =//m.media-amazon.com/images/I/614EkRctkGL._AC_UF350,350_QL80_.jpg", "CleanCare", 114m, "Mild irritation may occur for sensitive skin.", null, null },
                    { new Guid("9efceda5-b6b8-40d2-9ecf-4d48aa19a2e1"), "personal care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "An a_ll-natural herbal oil that promotes hair growth and reduces hair fall.", "For external use only. Keep out of reach of children.", "Herbal Hair Oil", "2024-12-15", "https =//www.araahskinmiracle.com/wp-content/uploads/2022/10/main-1l-hair.jpg.webp", "Nature's Essence", 999m, "Avoid contact with eyes; may cause eye irritation.", null, null },
                    { new Guid("a0160ae6-6fbf-4d35-90fd-246936583349"), "personal care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "A de_eply hydrating body lotion that nourishes and softens the skin.", "Th_is_ product is not intended to diagnose, treat, cure, or prevent any disease.", "Vaseline Sun Protection SPF 30 Body Lotion", "2025-12-31", "https =//images-static.nykaa.com/media/catalog/product/6/c/6c1a17cVASEL00000100_1.jpg?tr=w-500", "EcoBeauty", 298m, "For external use only. Avoid contact with eyes. Discontinue use if irritation occurs.", null, null },
                    { new Guid("a424b19d-387e-4f66-a790-9fbe53a947ae"), "personal care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "High_ protection sunscreen to shield your skin from harmful UV rays.", "Apply generously before sun exposure.", "Sunscreen SPF 50", "2023-09-30", "https =//www.lotusherbals.com/cdn/shop/files/SPF50_Frontcopy3.jpg?v=1713771327", "SunGuard", 400m, "May cause rash or irritation in some individuals.", null, null },
                    { new Guid("a52e0262-522a-4f2f-a3a8-c872bf13deae"), "personal care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "A na_tural shampoo enriched with herbal extracts for healthy, shiny hair.", "For external use only. Avoid contact with eyes.", "head and shoulders Shampoo", "2025-12-31", "https =//images-cdn.ubuy.co.in/64f07850e7d397721505a2f8-head-and-shoulders-dandruff-shampoo.jpg", "head and shoulders", 265m, "None reported", null, null },
                    { new Guid("a6951bd4-5d28-4fc0-8293-f26cd35d5097"), "personal care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "A ge_ntle shampoo that helps control dandruff while nourishing the scalp.", "For external use only. Rinse thoroughly if contact with eyes occurs.", "Dove Anti-Dandruff Shampoo", "2024-08-15", "https =//www.quickpantry.in/cdn/shop/products/dove-dandruff-care-shampoo-quick-pantry_500x500.jpg?v=1710539099", "Dove", 299m, "May cause mild irritation if it gets into eyes.", null, null },
                    { new Guid("a7280712-e04c-4790-8216-5cd919f1dbad"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Tear-free formula for gentle cleansing.", "Rinse thoroughly to avoid residue.", "Citaphil Baby Shampoo", "2024-12-31", "https =//onemg.gumlet.io/l_watermark_346,w_480,h_480/a_ignore,w_480,h_480,c_fit,q_auto,f_auto/crbtcpjcdab7csqm7l7i.jpg", "GentleCare", 584m, "Mild eye irritation if it gets into eyes.", null, null },
                    { new Guid("a9387756-7981-4e40-9ddf-dfd332943079"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Moisturizes and nourishes baby's skin.", "Test on small area before use.", "Johnson's Coconut Oil Baby Body Lotion", "2025-04-15", "https =//images-cdn.ubuy.co.in/64fd8f25cc10ab0dd8722d7c-johnsons-moisturizing-pink-baby-body.jpg", "SoftSkin", 499m, "Rare skin irritation in sensitive skin.", null, null },
                    { new Guid("aa10651e-dc26-40b8-b441-74b9ab025eac"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Gentle and effective for cleaning baby's skin.", "Use only as directed. Discontinue if irritation occurs.", "Jphnson's Baby Wipes", "2025-08-10", "https =//m.media-amazon.com/images/I/61jXR7o-W7L.jpg", "CleanBaby", 199m, "Possible allergic reaction to fragrance.", null, null },
                    { new Guid("b674f064-96bf-4078-ade0-9c39e590477d"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Relieves teething pain and discomfort.", "Change diapers frequently to avoid prolonged exposure to moisture. If irritation occurs, discontinue use and consult a pediatrician.", "Pappers All round Protection", "2024-09-20", "https =//www.bigbasket.com/media/uploads/p/xl/40268401_2-pampers-diaper-pants-new()-born-all-round-protection-anti-rash-blanket-new()-improved.jpg", "HappyTeeth", 279m, "Possible skin irritation or diaper rash.", null, null },
                    { new Guid("bc29b5dc-d59f-4466-8e2a-7501ab9af260"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Protects baby's skin from harmful UV rays.", "Change diapers frequently to avoid prolonged exposure to moisture. If irritation occurs, discontinue use and consult a pediatrician.", "Manypoko Standard", "2025-05-30", "https =//5.imimg.com/data5/SELLER/Default/2023/5/308799233/GZ/YB/SY/73826082/mamy-poko-pants-standard-diaper.jpg", "SunSafe", 449m, "Possible skin irritation or diaper rash.", null, null },
                    { new Guid("c052045e-3862-49bb-a003-ed49fa7e998a"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Mild and gentle formula for baby's bath time.", "Avoid contact with eyes. Rinse thoroughly.", "Himalaya baby Massage Oil", "2024-11-25", "https =//himalayawellness.in/cdn/shop/products/Baby-Massage-Oil.jpg?v=1622100409", "BathTime", 250m, "Possible mild eye irritation.", null, null },
                    { new Guid("c3cbf42e-9e95-4388-a23b-a8ba8f01ce96"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Nourishes and relaxes baby's skin.", "Test on a small area before full application.", "Johnson's Non-Sticky Oil ", "2026-03-15", "https =//www.jiomart.com/images/product/original/491947406/johnson-s-baby-cottontouch-new()born-massage-oil-100-ml-product-images-o491947406-p590514099-0-202308230923.jpg?im=Resize=(1000,1000)", "TenderTouch", 430m, "Rare skin irritation.", null, null },
                    { new Guid("c752559f-6a87-4d7f-a7f3-e33d49d27e1e"), "Baby Care", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Helps relieve baby's nasal congestion.", "For external use only. Do not apply to broken skin.", "Vapor Rub", "2025-12-20", "https =//m.media-amazon.com/images/I/71bBjtfhfVL.jpg", "BreatheEasy", 50m, "Possible skin irritation.", null, null },
                    { new Guid("d0578e48-ddb2-42a0-8263-28e07f988209"), "Ayurveda", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Trip_hala Churna is a combination of three fruits and is used for digestive and detoxification purposes in Ayurveda.", "Consult a healthcare professional before use.", "Triphala Churna", "2025-12-31", "https =//www.patanjaliayurved.net/assets/product_images/400x500/16883660031.png", "Patanjali Ayurved Limited", 150m, "No known side effects when used as directed.", null, null },
                    { new Guid("d1ac7ec4-2aee-4b8a-b483-27d906ca159c"), "Ayurveda", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Ashw_agandha Capsules are used to reduce stress, improve concentration, and boost energy levels.", "Not recommended for pregnant or nursing women.", "Ashwagandha Capsules", "2024-11-30", "https =//m.media-amazon.com/images/I/61eNW65rU0L._AC_UF1000,1000_QL80_.jpg", "Himalaya Wellness", 250m, "May cause mild gastrointestinal discomfort in some individuals.", null, null },
                    { new Guid("d4f45f18-db0e-43dd-b3fd-dfd41f25d457"), "Ayurveda", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Neem Face Wash is formulated with neem extracts to cleanse and purify the skin, suitable for oily and acne-prone skin types.", "Avoid contact with eyes; rinse thoroughly with water if contact occurs.", "Neem Face Wash", "2023-08-31", "https =//m.media-amazon.com/images/I/51tXjE2WQQL.jpg", "Himalaya Wellness", 120m, "No known side effects when used topically.", null, null },
                    { new Guid("d78d6ff1-004c-4b6b-8d08-0294007af0b3"), "Ayurveda", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Trikatu Churna is a blend of three pungent herbs used to support digestion, metabolism, and respiratory health in Ayurveda.", "Consult a qualified healthcare practitioner before use.", "Trikatu Churna", "2023-06-30", "https =//m.media-amazon.com/images/I/81fbE1aS5mL.jpg", "Baidyanath", 180m, "May cause a warming sensation in the stomach.", null, null },
                    { new Guid("eae5cc5e-5e6b-4f80-ae1f-9d86b3862ab8"), "Ayurveda", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Amla_ Juice is rich in Vitamin C and antioxidants, known for its rejuvenating and immune-boosting properties in Ayurveda.", "Best consumed as per recommended dosage; excessive consumption may lead to digestive discomfort.", "Amla Juice", "2024-09-30", "https =//www.patanjaliayurved.net/assets/product_images/thumbs/350_360_1690962103AmlaJuice1ltrNew()1.png", "Patanjali Ayurved Limited", 180m, "May cause mild acidity in some individuals.", null, null },
                    { new Guid("eb44a1c5-bb90-4219-9f42-9dd1699e2b54"), "Health Devices", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "A digital blood pressure monitor for accurate readings.", "Consult a healthcare professional for medical advice.", "Blood Pressure Monitor", "N/A", "https =//m.media-amazon.com/images/I/71-qOprKrIL.jpg", "HealthTech Inc.", 1049m, "None", null, null },
                    { new Guid("f1c371bd-8b67-465b-b0a4-f6d196842fc7"), "Health Devices", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "A digital blood glucose meter used to measure how much glucose (a type of sugar) is in the blood.", "Consult a healthcare professional for medical advice.", "Glucometer", "N/A", "https =//m.media-amazon.com/images/I/317TDpZziaL.jpg", "FitLife Technologies", 695m, "None", null, null },
                    { new Guid("f42f502a-5659-41b6-9d43-26e906e15c69"), "Health Devices", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Accurate digital thermometer for measuring body temperature.", "Read instructions carefully before use.", "Digital Thermometer", "N/A", "https =//m.media-amazon.com/images/I/41Lz9yz0vHL._AC_UF1000,1000_QL80_.jpg", "MediSense Innovations", 199m, "None", null, null },
                    { new Guid("f71859d1-52e9-4155-bc70-2fb71cb97c72"), "Nutritional Drinks & Supplements", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "High-quality protein powder for muscle recovery and growth.", "C_onsult your doctor before starting any new() supplement regimen.", "Protein Powder", "2025-12-31", "https =//m.media-amazon.com/images/I/61ZKpqtTJ2L.jpg", "FitnessNutri", 389m, "May cause mild bloating in some individuals.", null, null },
                    { new Guid("fd71f163-dd72-44cf-810d-c88599b076e6"), "Nutritional Drinks & Supplements", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Dail_y multivitamin tablets to support overall health and immunity.", "Keep out of reach of children.", "Multivitamin Tablets", "2025-09-30", "https =//m.media-amazon.com/images/I/519FFsSSOAL._AC_UF1000,1000_QL80_.jpg", "HealthPlus", 359m, "None reported.", null, null },
                    { new Guid("fd73a2ef-e3df-4b86-bf2b-9b268dbaefb0"), "Nutritional Drinks & Supplements", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Omeg_a-3 fish oil capsules for heart health and joint support.", "Store in a cool, dry place.", "Fish Oil Capsules", "2025-06-15", "https =//m.media-amazon.com/images/I/71RcH-GkD6L._AC_UF894,1000_QL80_.jpg", "OmegaHealth", 949m, "May cause fishy aftertaste.", null, null },
                    { new Guid("fed00935-9d29-4340-b877-1d08c99b64a0"), "Nutritional Drinks & Supplements", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Instant energy drink mix with vitamins and minerals.", "Not recommended for pregnant women or individuals sensitive to caffeine.", "Energy Drink Mix", "2025-11-20", "https =//cdn.gaiagoodhealth.com/wp-content/uploads/2023/07/21133855/550x370-orange.png", "BoostEnergy", 128m, "C_ontains caffeine; may cause sleeplessness if consumed late in the day.", null, null },
                    { new Guid("ff75f7ff-ae64-4362-bd2d-c69cfb755a5c"), "Nutritional Drinks & Supplements", null, 100, new DateTime(2025, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), "admin", "Probiotic-rich yogurt for digestive health and gut balance.", "Refrigerate after opening.", "Probiotic Yogurt", "2025-08-05", "https =//english.varthabharati.in/storage/uploads/health/drinkB_vb_14.jpeg", "BioHealth", 100m, "M_ay cause mild digestive discomfort in sensitive individuals.", null, null }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Drugs");

            migrationBuilder.DropTable(
                name: "Logs");
        }
    }
}
